### ISSUE TITLE
Добавить к решению модульные тесты

### ISSUE THREAD

**Issue by mezhmal** [skeriy/validator-battlefield#2]
Используя [UnitTest](https://docs.python.org/3/library/unittest.html) написать тесты для сценариев, указанных в задаче [Ошибка валидатора](https://github.com/skeriy/validator-battlefield/issues/1).

Тесты сложить в папку `test`.

**Comment by skeriy** [comment]
Файл с тестами по ошибкам добавлены в репозиторий.
